#include "rn4871_defs.h"

#include "rn4871_api.h"
#include "rn4871_types.h"

RN4871_STATIC_CONST char RN4871_ERRORS[RN4871_ERROR_MAX][ERROR_CODE_LEN_MAX] = {
    [RN4871_ERROR_NONE] = "NONE",
    [RN4871_ERROR_BAD_PARAMETER] = "BAD_PARAMETER",
    [RN4871_ERROR_UART_FAIL] = "UART_FAIL",
    [RN4871_ERROR_CMD_UNKNOWN] = "COMMAND_UNKNOWN",
    [RN4871_ERROR_NO_MODE_COMMAND] = "NO_COMMAND_MODE",
    [RN4871_ERROR_NO_MODE_DATA] = "NO_DATA_MODE",
    [RN4871_ERROR_NO_TRANSPARENT_UART] = "NO_TRANSPARENT_UART",
    [RN4871_ERROR_NO_CONNECTED] = "NO_CONNECTED",
    [RN4871_ERROR_NO_STREAMING] = "NO_STREAMING",
    [RN4871_ERROR_UNKNOWN] = "UNKNOWN",
};

RN4871_STATIC_CONST char RN4871_COMMANDS[RN4871_COMMAND_MAX][COMMAND_LEN_MAX] =
    {
        [RN4871_CMD_MODE_ENTER] = "$$$",
        [RN4871_CMD_MODE_QUIT] = "---",
        [RN4871_CMD_REBOOT] = "R",
        [RN4871_CMD_RESET_FACTORY] = "SF",
        [RN4871_CMD_SET_BT_NAME] = "S-",
        [RN4871_CMD_SET_DEVICE_NAME] = "SN",
        [RN4871_CMD_GET_DEVICE_NAME] = "GN",
        [RN4871_CMD_SET_SERVICES] = "SS",
        [RN4871_CMD_DUMP_INFOS] = "D",
        [RN4871_CMD_GET_VERSION] = "V",
        [RN4871_CMD_CLEAR_ALL_SERVICES] = "PZ",
        [RN4871_CMD_CREATE_PRIVATE_SERVICE] = "PS",
        [RN4871_CMD_CREATE_PRIVATE_CHARACTERISTIC] = "PC",
        [RN4871_CMD_SERVER_WRITE_CHARACTERISTIC] = "SHW",
        [RN4871_CMD_SERVER_READ_CHARACTERISTIC] = "SHR",
        [RN4871_CMD_NONE] = "",
};